<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>..\SmartSaver\Resources\tray_icon.ico</ApplicationIcon>
    <Title>DASMO CYBER CAFE TOOLS</Title>
    <AssemblyTitle>DASMO CYBER CAFE TOOLS</AssemblyTitle>
    <Description>DASMO CYBER CAFE TOOLS</Description>
    <Product>DASMO CYBER CAFE TOOLS</Product>
    <Company>DASMO Cyber Cafe</Company>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartSaver\SmartSaver.csproj" />
  </ItemGroup>
</Project>
